# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apriltag.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61priltag.proto\x12\x08\x61priltag\x1a\nbase.proto\"n\n\x08\x41priltag\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x1d\n\x08position\x18\x02 \x01(\x0b\x32\x0b.base.Vec3f\x12\x1f\n\nquaternion\x18\x03 \x01(\x0b\x32\x0b.base.Vec4f\x12\x0f\n\x07tag_num\x18\x04 \x01(\rb\x06proto3')



_APRILTAG = DESCRIPTOR.message_types_by_name['Apriltag']
Apriltag = _reflection.GeneratedProtocolMessageType('Apriltag', (_message.Message,), {
  'DESCRIPTOR' : _APRILTAG,
  '__module__' : 'apriltag_pb2'
  # @@protoc_insertion_point(class_scope:apriltag.Apriltag)
  })
_sym_db.RegisterMessage(Apriltag)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _APRILTAG._serialized_start=40
  _APRILTAG._serialized_end=150
# @@protoc_insertion_point(module_scope)
