# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbase.proto\x12\x04\x62\x61se\"(\n\x05Vec3f\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"(\n\x05Vec3d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"3\n\x05Vec4f\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\";\n\x04Rect\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\"N\n\x03GPS\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x01\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x01(\x01*6\n\x10\x43oordinateSystem\x12\n\n\x06GROUND\x10\x00\x12\x08\n\x04\x42ODY\x10\x01\x12\x0c\n\x08RELATIVE\x10\x02\x62\x06proto3')

_COORDINATESYSTEM = DESCRIPTOR.enum_types_by_name['CoordinateSystem']
CoordinateSystem = enum_type_wrapper.EnumTypeWrapper(_COORDINATESYSTEM)
GROUND = 0
BODY = 1
RELATIVE = 2


_VEC3F = DESCRIPTOR.message_types_by_name['Vec3f']
_VEC3D = DESCRIPTOR.message_types_by_name['Vec3d']
_VEC4F = DESCRIPTOR.message_types_by_name['Vec4f']
_RECT = DESCRIPTOR.message_types_by_name['Rect']
_GPS = DESCRIPTOR.message_types_by_name['GPS']
Vec3f = _reflection.GeneratedProtocolMessageType('Vec3f', (_message.Message,), {
  'DESCRIPTOR' : _VEC3F,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:base.Vec3f)
  })
_sym_db.RegisterMessage(Vec3f)

Vec3d = _reflection.GeneratedProtocolMessageType('Vec3d', (_message.Message,), {
  'DESCRIPTOR' : _VEC3D,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:base.Vec3d)
  })
_sym_db.RegisterMessage(Vec3d)

Vec4f = _reflection.GeneratedProtocolMessageType('Vec4f', (_message.Message,), {
  'DESCRIPTOR' : _VEC4F,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:base.Vec4f)
  })
_sym_db.RegisterMessage(Vec4f)

Rect = _reflection.GeneratedProtocolMessageType('Rect', (_message.Message,), {
  'DESCRIPTOR' : _RECT,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:base.Rect)
  })
_sym_db.RegisterMessage(Rect)

GPS = _reflection.GeneratedProtocolMessageType('GPS', (_message.Message,), {
  'DESCRIPTOR' : _GPS,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:base.GPS)
  })
_sym_db.RegisterMessage(GPS)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COORDINATESYSTEM._serialized_start=298
  _COORDINATESYSTEM._serialized_end=352
  _VEC3F._serialized_start=20
  _VEC3F._serialized_end=60
  _VEC3D._serialized_start=62
  _VEC3D._serialized_end=102
  _VEC4F._serialized_start=104
  _VEC4F._serialized_end=155
  _RECT._serialized_start=157
  _RECT._serialized_end=216
  _GPS._serialized_start=218
  _GPS._serialized_end=296
# @@protoc_insertion_point(module_scope)
