# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import camera_pb2 as camera__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x61mera_service.proto\x12\x08pbCamera\x1a\x0c\x63\x61mera.proto\"\x0b\n\tParamNone\"+\n\nCommandAck\x12\x1d\n\x03ret\x18\x01 \x01(\x0e\x32\x10.pbCamera.CmdErr*-\n\x06\x43mdErr\x12\x10\n\x0c\x43\x41M_ERR_NONE\x10\x00\x12\x11\n\x0c\x43\x41M_ERR_PARM\x10\x80\x02\x32\xdd\x04\n\x0c\x43\x61meraServer\x12\x33\n\x04Init\x12\x13.pbCamera.ParamNone\x1a\x14.pbCamera.CommandAck\"\x00\x12=\n\x0eSetCameraParam\x12\x13.camera.SetMetadata\x1a\x14.pbCamera.CommandAck\"\x00\x12\x39\n\x0eGetCameraParam\x12\x13.pbCamera.ParamNone\x1a\x10.camera.Metadata\"\x00\x12;\n\x0cStartPreview\x12\x13.pbCamera.ParamNone\x1a\x14.pbCamera.CommandAck\"\x00\x12:\n\x0bStopPreview\x12\x13.pbCamera.ParamNone\x1a\x14.pbCamera.CommandAck\"\x00\x12\x39\n\nStartVideo\x12\x13.pbCamera.ParamNone\x1a\x14.pbCamera.CommandAck\"\x00\x12\x38\n\tStopVideo\x12\x13.pbCamera.ParamNone\x1a\x14.pbCamera.CommandAck\"\x00\x12;\n\x0cTakeSnapshot\x12\x13.pbCamera.ParamNone\x1a\x14.pbCamera.CommandAck\"\x00\x12;\n\x0cStopSnapshot\x12\x13.pbCamera.ParamNone\x1a\x14.pbCamera.CommandAck\"\x00\x12\x36\n\x0c\x43\x61meraStatus\x12\x13.pbCamera.ParamNone\x1a\r.camera.Event\"\x00\x30\x01\x62\x06proto3')

_CMDERR = DESCRIPTOR.enum_types_by_name['CmdErr']
CmdErr = enum_type_wrapper.EnumTypeWrapper(_CMDERR)
CAM_ERR_NONE = 0
CAM_ERR_PARM = 256


_PARAMNONE = DESCRIPTOR.message_types_by_name['ParamNone']
_COMMANDACK = DESCRIPTOR.message_types_by_name['CommandAck']
ParamNone = _reflection.GeneratedProtocolMessageType('ParamNone', (_message.Message,), {
  'DESCRIPTOR' : _PARAMNONE,
  '__module__' : 'camera_service_pb2'
  # @@protoc_insertion_point(class_scope:pbCamera.ParamNone)
  })
_sym_db.RegisterMessage(ParamNone)

CommandAck = _reflection.GeneratedProtocolMessageType('CommandAck', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDACK,
  '__module__' : 'camera_service_pb2'
  # @@protoc_insertion_point(class_scope:pbCamera.CommandAck)
  })
_sym_db.RegisterMessage(CommandAck)

_CAMERASERVER = DESCRIPTOR.services_by_name['CameraServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CMDERR._serialized_start=106
  _CMDERR._serialized_end=151
  _PARAMNONE._serialized_start=48
  _PARAMNONE._serialized_end=59
  _COMMANDACK._serialized_start=61
  _COMMANDACK._serialized_end=104
  _CAMERASERVER._serialized_start=154
  _CAMERASERVER._serialized_end=759
# @@protoc_insertion_point(module_scope)
