# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\"}\n\x0fManufactureInfo\x12\r\n\x05model\x18\x01 \x01(\t\x12\n\n\x02sn\x18\x02 \x01(\t\x12\x18\n\x10manufacture_data\x18\x03 \x01(\t\x12\x12\n\nhw_version\x18\x04 \x01(\t\x12\r\n\x05hw_id\x18\x05 \x01(\t\x12\x12\n\nsw_version\x18\x06 \x01(\t\"9\n\x0eHoverUsageInfo\x12\x10\n\x08\x66ly_time\x18\x01 \x01(\r\x12\x15\n\rfly_time_last\x18\x02 \x01(\r\"R\n\nMemoryInfo\x12\"\n\x1ainternal_not_exist_or_full\x18\x01 \x01(\x08\x12 \n\x18sdcard_not_exist_or_full\x18\x02 \x01(\x08\"0\n\tWifiEvent\x12#\n\x06ipinfo\x18\x01 \x03(\x0b\x32\x13.common.Stationinfo\"2\n\x0bStationinfo\x12\x0b\n\x03snr\x18\x01 \x01(\x05\x12\n\n\x02nf\x18\x02 \x01(\x05\x12\n\n\x02ip\x18\x03 \x01(\t\"0\n\tTransMode\x12#\n\x04mode\x18\x01 \x01(\x0e\x32\x15.common.TransModeEnum\"\r\n\x0bWifiGetFreq\"5\n\x0bWifiSetFreq\x12&\n\x08\x66reqmode\x18\x01 \x01(\x0e\x32\x14.common.WifiFreqMode\"h\n\x0bWifiCommand\x12&\n\x07setfreq\x18\x01 \x01(\x0b\x32\x13.common.WifiSetFreqH\x00\x12&\n\x07getfreq\x18\x02 \x01(\x0b\x32\x13.common.WifiGetFreqH\x00\x42\t\n\x07\x63ommand\"\\\n\x0eWifiCommandAck\x12\r\n\x05is_ok\x18\x01 \x01(\x08\x12(\n\x08\x66reqmode\x18\x02 \x01(\x0e\x32\x14.common.WifiFreqModeH\x00\x42\x11\n\x0f\x61\x64\x64ition_config\"\x1f\n\x0bTimeSetting\x12\x10\n\x08timezone\x18\x01 \x01(\x05*(\n\nMemoryType\x12\x0c\n\x08INTERNAL\x10\x00\x12\x0c\n\x08\x45XTERNAL\x10\x01*,\n\rTransModeEnum\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04WIFI\x10\x01\x12\x07\n\x03\x46PV\x10\x02*4\n\x0cWifiFreqMode\x12\x12\n\x0eWIFI_FREQ_2_4G\x10\x00\x12\x10\n\x0cWIFI_FREQ_5G\x10\x01\x42#\n\x16\x63n.zerozero.proto.h130P\x01\xa2\x02\x06H130PBb\x06proto3')

_MEMORYTYPE = DESCRIPTOR.enum_types_by_name['MemoryType']
MemoryType = enum_type_wrapper.EnumTypeWrapper(_MEMORYTYPE)
_TRANSMODEENUM = DESCRIPTOR.enum_types_by_name['TransModeEnum']
TransModeEnum = enum_type_wrapper.EnumTypeWrapper(_TRANSMODEENUM)
_WIFIFREQMODE = DESCRIPTOR.enum_types_by_name['WifiFreqMode']
WifiFreqMode = enum_type_wrapper.EnumTypeWrapper(_WIFIFREQMODE)
INTERNAL = 0
EXTERNAL = 1
NONE = 0
WIFI = 1
FPV = 2
WIFI_FREQ_2_4G = 0
WIFI_FREQ_5G = 1


_MANUFACTUREINFO = DESCRIPTOR.message_types_by_name['ManufactureInfo']
_HOVERUSAGEINFO = DESCRIPTOR.message_types_by_name['HoverUsageInfo']
_MEMORYINFO = DESCRIPTOR.message_types_by_name['MemoryInfo']
_WIFIEVENT = DESCRIPTOR.message_types_by_name['WifiEvent']
_STATIONINFO = DESCRIPTOR.message_types_by_name['Stationinfo']
_TRANSMODE = DESCRIPTOR.message_types_by_name['TransMode']
_WIFIGETFREQ = DESCRIPTOR.message_types_by_name['WifiGetFreq']
_WIFISETFREQ = DESCRIPTOR.message_types_by_name['WifiSetFreq']
_WIFICOMMAND = DESCRIPTOR.message_types_by_name['WifiCommand']
_WIFICOMMANDACK = DESCRIPTOR.message_types_by_name['WifiCommandAck']
_TIMESETTING = DESCRIPTOR.message_types_by_name['TimeSetting']
ManufactureInfo = _reflection.GeneratedProtocolMessageType('ManufactureInfo', (_message.Message,), {
  'DESCRIPTOR' : _MANUFACTUREINFO,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.ManufactureInfo)
  })
_sym_db.RegisterMessage(ManufactureInfo)

HoverUsageInfo = _reflection.GeneratedProtocolMessageType('HoverUsageInfo', (_message.Message,), {
  'DESCRIPTOR' : _HOVERUSAGEINFO,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.HoverUsageInfo)
  })
_sym_db.RegisterMessage(HoverUsageInfo)

MemoryInfo = _reflection.GeneratedProtocolMessageType('MemoryInfo', (_message.Message,), {
  'DESCRIPTOR' : _MEMORYINFO,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.MemoryInfo)
  })
_sym_db.RegisterMessage(MemoryInfo)

WifiEvent = _reflection.GeneratedProtocolMessageType('WifiEvent', (_message.Message,), {
  'DESCRIPTOR' : _WIFIEVENT,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.WifiEvent)
  })
_sym_db.RegisterMessage(WifiEvent)

Stationinfo = _reflection.GeneratedProtocolMessageType('Stationinfo', (_message.Message,), {
  'DESCRIPTOR' : _STATIONINFO,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.Stationinfo)
  })
_sym_db.RegisterMessage(Stationinfo)

TransMode = _reflection.GeneratedProtocolMessageType('TransMode', (_message.Message,), {
  'DESCRIPTOR' : _TRANSMODE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.TransMode)
  })
_sym_db.RegisterMessage(TransMode)

WifiGetFreq = _reflection.GeneratedProtocolMessageType('WifiGetFreq', (_message.Message,), {
  'DESCRIPTOR' : _WIFIGETFREQ,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.WifiGetFreq)
  })
_sym_db.RegisterMessage(WifiGetFreq)

WifiSetFreq = _reflection.GeneratedProtocolMessageType('WifiSetFreq', (_message.Message,), {
  'DESCRIPTOR' : _WIFISETFREQ,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.WifiSetFreq)
  })
_sym_db.RegisterMessage(WifiSetFreq)

WifiCommand = _reflection.GeneratedProtocolMessageType('WifiCommand', (_message.Message,), {
  'DESCRIPTOR' : _WIFICOMMAND,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.WifiCommand)
  })
_sym_db.RegisterMessage(WifiCommand)

WifiCommandAck = _reflection.GeneratedProtocolMessageType('WifiCommandAck', (_message.Message,), {
  'DESCRIPTOR' : _WIFICOMMANDACK,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.WifiCommandAck)
  })
_sym_db.RegisterMessage(WifiCommandAck)

TimeSetting = _reflection.GeneratedProtocolMessageType('TimeSetting', (_message.Message,), {
  'DESCRIPTOR' : _TIMESETTING,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.TimeSetting)
  })
_sym_db.RegisterMessage(TimeSetting)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026cn.zerozero.proto.h130P\001\242\002\006H130PB'
  _MEMORYTYPE._serialized_start=749
  _MEMORYTYPE._serialized_end=789
  _TRANSMODEENUM._serialized_start=791
  _TRANSMODEENUM._serialized_end=835
  _WIFIFREQMODE._serialized_start=837
  _WIFIFREQMODE._serialized_end=889
  _MANUFACTUREINFO._serialized_start=24
  _MANUFACTUREINFO._serialized_end=149
  _HOVERUSAGEINFO._serialized_start=151
  _HOVERUSAGEINFO._serialized_end=208
  _MEMORYINFO._serialized_start=210
  _MEMORYINFO._serialized_end=292
  _WIFIEVENT._serialized_start=294
  _WIFIEVENT._serialized_end=342
  _STATIONINFO._serialized_start=344
  _STATIONINFO._serialized_end=394
  _TRANSMODE._serialized_start=396
  _TRANSMODE._serialized_end=444
  _WIFIGETFREQ._serialized_start=446
  _WIFIGETFREQ._serialized_end=459
  _WIFISETFREQ._serialized_start=461
  _WIFISETFREQ._serialized_end=514
  _WIFICOMMAND._serialized_start=516
  _WIFICOMMAND._serialized_end=620
  _WIFICOMMANDACK._serialized_start=622
  _WIFICOMMANDACK._serialized_end=714
  _TIMESETTING._serialized_start=716
  _TIMESETTING._serialized_end=747
# @@protoc_insertion_point(module_scope)
