# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config_sensors.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63onfig_sensors.proto\x12\x06\x63onfig\"\x1b\n\tCfgVector\x12\x0e\n\x06values\x18\x01 \x03(\x02\",\n\tCfgMatrix\x12\x1f\n\x04rows\x18\x01 \x03(\x0b\x32\x11.config.CfgVector\"T\n\x0f\x43\x66gLinearAdjust\x12 \n\x05scale\x18\x01 \x01(\x0b\x32\x11.config.CfgVector\x12\x1f\n\x04\x62ias\x18\x02 \x01(\x0b\x32\x11.config.CfgVector\"\xa0\x01\n\x0c\x43\x66gIMUConfig\x12&\n\x05\x61\x63\x63\x65l\x18\x01 \x01(\x0b\x32\x17.config.CfgLinearAdjust\x12%\n\x04gyro\x18\x02 \x01(\x0b\x32\x17.config.CfgLinearAdjust\x12\x1c\n\x01R\x18\x03 \x01(\x0b\x32\x11.config.CfgMatrix\x12#\n\x08rotation\x18\x04 \x01(\x0b\x32\x11.config.CfgVector\"0\n\x10\x43\x66gOptflowConfig\x12\x1c\n\x01R\x18\x01 \x01(\x0b\x32\x11.config.CfgMatrix\"`\n\x10\x43\x66gSensorsConfig\x12!\n\x03imu\x18\x01 \x03(\x0b\x32\x14.config.CfgIMUConfig\x12)\n\x07optflow\x18\x02 \x03(\x0b\x32\x18.config.CfgOptflowConfig')



_CFGVECTOR = DESCRIPTOR.message_types_by_name['CfgVector']
_CFGMATRIX = DESCRIPTOR.message_types_by_name['CfgMatrix']
_CFGLINEARADJUST = DESCRIPTOR.message_types_by_name['CfgLinearAdjust']
_CFGIMUCONFIG = DESCRIPTOR.message_types_by_name['CfgIMUConfig']
_CFGOPTFLOWCONFIG = DESCRIPTOR.message_types_by_name['CfgOptflowConfig']
_CFGSENSORSCONFIG = DESCRIPTOR.message_types_by_name['CfgSensorsConfig']
CfgVector = _reflection.GeneratedProtocolMessageType('CfgVector', (_message.Message,), {
  'DESCRIPTOR' : _CFGVECTOR,
  '__module__' : 'config_sensors_pb2'
  # @@protoc_insertion_point(class_scope:config.CfgVector)
  })
_sym_db.RegisterMessage(CfgVector)

CfgMatrix = _reflection.GeneratedProtocolMessageType('CfgMatrix', (_message.Message,), {
  'DESCRIPTOR' : _CFGMATRIX,
  '__module__' : 'config_sensors_pb2'
  # @@protoc_insertion_point(class_scope:config.CfgMatrix)
  })
_sym_db.RegisterMessage(CfgMatrix)

CfgLinearAdjust = _reflection.GeneratedProtocolMessageType('CfgLinearAdjust', (_message.Message,), {
  'DESCRIPTOR' : _CFGLINEARADJUST,
  '__module__' : 'config_sensors_pb2'
  # @@protoc_insertion_point(class_scope:config.CfgLinearAdjust)
  })
_sym_db.RegisterMessage(CfgLinearAdjust)

CfgIMUConfig = _reflection.GeneratedProtocolMessageType('CfgIMUConfig', (_message.Message,), {
  'DESCRIPTOR' : _CFGIMUCONFIG,
  '__module__' : 'config_sensors_pb2'
  # @@protoc_insertion_point(class_scope:config.CfgIMUConfig)
  })
_sym_db.RegisterMessage(CfgIMUConfig)

CfgOptflowConfig = _reflection.GeneratedProtocolMessageType('CfgOptflowConfig', (_message.Message,), {
  'DESCRIPTOR' : _CFGOPTFLOWCONFIG,
  '__module__' : 'config_sensors_pb2'
  # @@protoc_insertion_point(class_scope:config.CfgOptflowConfig)
  })
_sym_db.RegisterMessage(CfgOptflowConfig)

CfgSensorsConfig = _reflection.GeneratedProtocolMessageType('CfgSensorsConfig', (_message.Message,), {
  'DESCRIPTOR' : _CFGSENSORSCONFIG,
  '__module__' : 'config_sensors_pb2'
  # @@protoc_insertion_point(class_scope:config.CfgSensorsConfig)
  })
_sym_db.RegisterMessage(CfgSensorsConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CFGVECTOR._serialized_start=32
  _CFGVECTOR._serialized_end=59
  _CFGMATRIX._serialized_start=61
  _CFGMATRIX._serialized_end=105
  _CFGLINEARADJUST._serialized_start=107
  _CFGLINEARADJUST._serialized_end=191
  _CFGIMUCONFIG._serialized_start=194
  _CFGIMUCONFIG._serialized_end=354
  _CFGOPTFLOWCONFIG._serialized_start=356
  _CFGOPTFLOWCONFIG._serialized_end=404
  _CFGSENSORSCONFIG._serialized_start=406
  _CFGSENSORSCONFIG._serialized_end=502
# @@protoc_insertion_point(module_scope)
