# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_engine.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ontrol_engine.proto\x12\x0e\x63ontrol_engine\"+\n\x1bSystemCommandAckGetKnobGear\x12\x0c\n\x04gear\x18\x01 \x01(\r\"<\n\rSystemCommand\x12+\n\x02id\x18\x01 \x01(\x0e\x32\x1f.control_engine.SystemCommandId\"l\n\x10SystemCommandAck\x12\r\n\x05is_ok\x18\x01 \x01(\x08\x12@\n\tknob_gear\x18\x02 \x01(\x0b\x32+.control_engine.SystemCommandAckGetKnobGearH\x00\x42\x07\n\x05param*6\n\x0fSystemCommandId\x12#\n\x1fSYSTEM_COMMAND_ID_GET_KNOB_GEAR\x10\x00\x62\x06proto3')

_SYSTEMCOMMANDID = DESCRIPTOR.enum_types_by_name['SystemCommandId']
SystemCommandId = enum_type_wrapper.EnumTypeWrapper(_SYSTEMCOMMANDID)
SYSTEM_COMMAND_ID_GET_KNOB_GEAR = 0


_SYSTEMCOMMANDACKGETKNOBGEAR = DESCRIPTOR.message_types_by_name['SystemCommandAckGetKnobGear']
_SYSTEMCOMMAND = DESCRIPTOR.message_types_by_name['SystemCommand']
_SYSTEMCOMMANDACK = DESCRIPTOR.message_types_by_name['SystemCommandAck']
SystemCommandAckGetKnobGear = _reflection.GeneratedProtocolMessageType('SystemCommandAckGetKnobGear', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMCOMMANDACKGETKNOBGEAR,
  '__module__' : 'control_engine_pb2'
  # @@protoc_insertion_point(class_scope:control_engine.SystemCommandAckGetKnobGear)
  })
_sym_db.RegisterMessage(SystemCommandAckGetKnobGear)

SystemCommand = _reflection.GeneratedProtocolMessageType('SystemCommand', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMCOMMAND,
  '__module__' : 'control_engine_pb2'
  # @@protoc_insertion_point(class_scope:control_engine.SystemCommand)
  })
_sym_db.RegisterMessage(SystemCommand)

SystemCommandAck = _reflection.GeneratedProtocolMessageType('SystemCommandAck', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMCOMMANDACK,
  '__module__' : 'control_engine_pb2'
  # @@protoc_insertion_point(class_scope:control_engine.SystemCommandAck)
  })
_sym_db.RegisterMessage(SystemCommandAck)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYSTEMCOMMANDID._serialized_start=257
  _SYSTEMCOMMANDID._serialized_end=311
  _SYSTEMCOMMANDACKGETKNOBGEAR._serialized_start=40
  _SYSTEMCOMMANDACKGETKNOBGEAR._serialized_end=83
  _SYSTEMCOMMAND._serialized_start=85
  _SYSTEMCOMMAND._serialized_end=145
  _SYSTEMCOMMANDACK._serialized_start=147
  _SYSTEMCOMMANDACK._serialized_end=255
# @@protoc_insertion_point(module_scope)
