# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exception_event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65xception_event.proto\x12\x0f\x65xception_event\"-\n\x05\x45vent\x12$\n\x02id\x18\x01 \x02(\x0e\x32\x18.exception_event.EventId\"2\n\x08\x45ventSet\x12&\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x16.exception_event.Event*\xa8\x01\n\x07\x45ventId\x12\x11\n\rEVENT_ID_NONE\x10\x00\x12\x16\n\x12\x45VENT_ID_HEARTBEAT\x10\x01\x12\x17\n\x13\x45VENT_ID_PRETAKEOFF\x10\x02\x12\x1b\n\x17\x45VENT_ID_PRETAKEOFFSTOP\x10\x03\x12\x1b\n\x17\x45VENT_ID_NORMAL_LANDING\x10\x04\x12\x1f\n\x1bSELFCHECK_BEFORE_PRETAKEOFF\x10\x05')

_EVENTID = DESCRIPTOR.enum_types_by_name['EventId']
EventId = enum_type_wrapper.EnumTypeWrapper(_EVENTID)
EVENT_ID_NONE = 0
EVENT_ID_HEARTBEAT = 1
EVENT_ID_PRETAKEOFF = 2
EVENT_ID_PRETAKEOFFSTOP = 3
EVENT_ID_NORMAL_LANDING = 4
SELFCHECK_BEFORE_PRETAKEOFF = 5


_EVENT = DESCRIPTOR.message_types_by_name['Event']
_EVENTSET = DESCRIPTOR.message_types_by_name['EventSet']
Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'exception_event_pb2'
  # @@protoc_insertion_point(class_scope:exception_event.Event)
  })
_sym_db.RegisterMessage(Event)

EventSet = _reflection.GeneratedProtocolMessageType('EventSet', (_message.Message,), {
  'DESCRIPTOR' : _EVENTSET,
  '__module__' : 'exception_event_pb2'
  # @@protoc_insertion_point(class_scope:exception_event.EventSet)
  })
_sym_db.RegisterMessage(EventSet)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENTID._serialized_start=142
  _EVENTID._serialized_end=310
  _EVENT._serialized_start=42
  _EVENT._serialized_end=87
  _EVENTSET._serialized_start=89
  _EVENTSET._serialized_end=139
# @@protoc_insertion_point(module_scope)
