# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fly_safe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66ly_safe.proto\x12\x08\x66ly_safe\"N\n\x07ZoneSet\x12\x0f\n\x07version\x18\x01 \x02(\t\x12\x13\n\x0blast_update\x18\x02 \x02(\x01\x12\x1d\n\x05zones\x18\x03 \x03(\x0b\x32\x0e.fly_safe.Zone\"\xf1\x02\n\x04Zone\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08\x62\x65gin_at\x18\x06 \x01(\x02\x12\x0e\n\x06\x65nd_at\x18\x07 \x01(\x02\x12\x14\n\x0clast_updated\x18\x08 \x01(\x02\x12.\n\x0b\x64\x61ta_source\x18\x0b \x01(\x0e\x32\x19.fly_safe.Zone.DataSource\x12!\n\x04type\x18\x0c \x01(\x0e\x32\x13.fly_safe.Zone.Type\x12\x0f\n\x07\x63ountry\x18\r \x01(\t\x12\x0c\n\x04\x63ity\x18\x0e \x01(\t\x12\x11\n\tlongitude\x18\x15 \x01(\x01\x12\x10\n\x08latitude\x18\x16 \x01(\x01\x12\x0e\n\x06height\x18\x17 \x01(\x02\x12!\n\tsub_areas\x18\x1e \x03(\x0b\x32\x0e.fly_safe.Area\"#\n\nDataSource\x12\n\n\x06\x41irMap\x10\x00\x12\t\n\x05Other\x10\x01\"\x13\n\x04Type\x12\x0b\n\x07Pending\x10\x00\"1\n\nCoordinate\x12\x11\n\tlongitude\x18\x01 \x02(\x01\x12\x10\n\x08latitude\x18\x02 \x02(\x01\"\xe1\x01\n\x04\x41rea\x12#\n\x05shape\x18\x01 \x02(\x0e\x32\x14.fly_safe.Area.Shape\x12\'\n\nlimit_type\x18\x02 \x02(\x0e\x32\x13.fly_safe.LimitType\x12$\n\x06points\x18\x03 \x03(\x0b\x32\x14.fly_safe.Coordinate\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x10\n\x08latitude\x18\x05 \x01(\x01\x12\x0e\n\x06radius\x18\x06 \x01(\x02\x12\x0e\n\x06height\x18\x07 \x01(\x02\" \n\x05Shape\x12\x0b\n\x07Polygon\x10\x00\x12\n\n\x06\x43ircle\x10\x01*\x86\x01\n\tLimitType\x12\t\n\x05NoFly\x10\x00\x12\x0f\n\x0bHeightLimit\x10\x01\x12\x11\n\rAuthorization\x10\x02\x12\x0b\n\x07Warning\x10\x03\x12\x15\n\x11StrengthenWarning\x10\x04\x12\x14\n\x10RegulationsLimit\x10\x05\x12\x10\n\x0cRecommendFly\x10\x06')

_LIMITTYPE = DESCRIPTOR.enum_types_by_name['LimitType']
LimitType = enum_type_wrapper.EnumTypeWrapper(_LIMITTYPE)
NoFly = 0
HeightLimit = 1
Authorization = 2
Warning = 3
StrengthenWarning = 4
RegulationsLimit = 5
RecommendFly = 6


_ZONESET = DESCRIPTOR.message_types_by_name['ZoneSet']
_ZONE = DESCRIPTOR.message_types_by_name['Zone']
_COORDINATE = DESCRIPTOR.message_types_by_name['Coordinate']
_AREA = DESCRIPTOR.message_types_by_name['Area']
_ZONE_DATASOURCE = _ZONE.enum_types_by_name['DataSource']
_ZONE_TYPE = _ZONE.enum_types_by_name['Type']
_AREA_SHAPE = _AREA.enum_types_by_name['Shape']
ZoneSet = _reflection.GeneratedProtocolMessageType('ZoneSet', (_message.Message,), {
  'DESCRIPTOR' : _ZONESET,
  '__module__' : 'fly_safe_pb2'
  # @@protoc_insertion_point(class_scope:fly_safe.ZoneSet)
  })
_sym_db.RegisterMessage(ZoneSet)

Zone = _reflection.GeneratedProtocolMessageType('Zone', (_message.Message,), {
  'DESCRIPTOR' : _ZONE,
  '__module__' : 'fly_safe_pb2'
  # @@protoc_insertion_point(class_scope:fly_safe.Zone)
  })
_sym_db.RegisterMessage(Zone)

Coordinate = _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), {
  'DESCRIPTOR' : _COORDINATE,
  '__module__' : 'fly_safe_pb2'
  # @@protoc_insertion_point(class_scope:fly_safe.Coordinate)
  })
_sym_db.RegisterMessage(Coordinate)

Area = _reflection.GeneratedProtocolMessageType('Area', (_message.Message,), {
  'DESCRIPTOR' : _AREA,
  '__module__' : 'fly_safe_pb2'
  # @@protoc_insertion_point(class_scope:fly_safe.Area)
  })
_sym_db.RegisterMessage(Area)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIMITTYPE._serialized_start=760
  _LIMITTYPE._serialized_end=894
  _ZONESET._serialized_start=28
  _ZONESET._serialized_end=106
  _ZONE._serialized_start=109
  _ZONE._serialized_end=478
  _ZONE_DATASOURCE._serialized_start=422
  _ZONE_DATASOURCE._serialized_end=457
  _ZONE_TYPE._serialized_start=459
  _ZONE_TYPE._serialized_end=478
  _COORDINATE._serialized_start=480
  _COORDINATE._serialized_end=529
  _AREA._serialized_start=532
  _AREA._serialized_end=757
  _AREA_SHAPE._serialized_start=725
  _AREA_SHAPE._serialized_end=757
# @@protoc_insertion_point(module_scope)
