# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gimbal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgimbal.proto\x12\x06gimbal\x1a\nbase.proto\"\xad\x01\n\rGimbalCommand\x12(\n\x07\x63ontrol\x18\x01 \x01(\x0b\x32\x15.gimbal.GimbalControlH\x00\x12\x35\n\x11\x62inocular_control\x18\x02 \x01(\x0b\x32\x18.gimbal.BinocularControlH\x00\x12+\n\tsync_time\x18\x03 \x01(\x0b\x32\x16.gimbal.GimbalSyncTimeH\x00\x42\x0e\n\x0c\x63ommand_type\"\x97\x01\n\x11GimbalAxisControl\x12\x31\n\x11\x63oordinate_system\x18\x01 \x01(\x0e\x32\x16.base.CoordinateSystem\x12\x19\n\x0fset_point_angle\x18\x02 \x01(\x02H\x00\x12$\n\x1aset_point_angular_velocity\x18\x03 \x01(\x02H\x00\x42\x0e\n\x0c\x63ontrol_type\"\x10\n\x0eGimbalSyncTime\"\x11\n\x0fGimbalSelfCheck\"\x14\n\x12\x42inocularSelfCheck\"\x8a\x01\n\rGimbalControl\x12\'\n\x04roll\x18\x01 \x01(\x0b\x32\x19.gimbal.GimbalAxisControl\x12(\n\x05pitch\x18\x02 \x01(\x0b\x32\x19.gimbal.GimbalAxisControl\x12&\n\x03yaw\x18\x03 \x01(\x0b\x32\x19.gimbal.GimbalAxisControl\"\x93\x01\n\x10\x42inocularControl\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x05\x12\r\n\x05\x61ngle\x18\x02 \x01(\x02\x12\x32\n\x04type\x18\x03 \x01(\x0e\x32$.gimbal.BinocularControl.ControlType\",\n\x0b\x43ontrolType\x12\t\n\x05\x41NGLE\x10\x00\x12\x12\n\x0e\x41NGLE_VELOCITY\x10\x01\"\xe2\x01\n\x0cGimbalStatus\x12/\n\x05state\x18\x01 \x01(\x0e\x32 .gimbal.GimbalStatus.GimbalState\x12\'\n\x12\x61ttitude_in_ground\x18\x02 \x01(\x0b\x32\x0b.base.Vec4f\x12%\n\x10\x61ttitude_in_body\x18\x03 \x01(\x0b\x32\x0b.base.Vec4f\"Q\n\x0bGimbalState\x12\n\n\x06NORMAL\x10\x00\x12\x14\n\x10NEED_CALIBRATION\x10\x01\x12\r\n\tNOT_FOUND\x10\x02\x12\x11\n\rERROR_UNKNOWN\x10\x03\x62\x06proto3')



_GIMBALCOMMAND = DESCRIPTOR.message_types_by_name['GimbalCommand']
_GIMBALAXISCONTROL = DESCRIPTOR.message_types_by_name['GimbalAxisControl']
_GIMBALSYNCTIME = DESCRIPTOR.message_types_by_name['GimbalSyncTime']
_GIMBALSELFCHECK = DESCRIPTOR.message_types_by_name['GimbalSelfCheck']
_BINOCULARSELFCHECK = DESCRIPTOR.message_types_by_name['BinocularSelfCheck']
_GIMBALCONTROL = DESCRIPTOR.message_types_by_name['GimbalControl']
_BINOCULARCONTROL = DESCRIPTOR.message_types_by_name['BinocularControl']
_GIMBALSTATUS = DESCRIPTOR.message_types_by_name['GimbalStatus']
_BINOCULARCONTROL_CONTROLTYPE = _BINOCULARCONTROL.enum_types_by_name['ControlType']
_GIMBALSTATUS_GIMBALSTATE = _GIMBALSTATUS.enum_types_by_name['GimbalState']
GimbalCommand = _reflection.GeneratedProtocolMessageType('GimbalCommand', (_message.Message,), {
  'DESCRIPTOR' : _GIMBALCOMMAND,
  '__module__' : 'gimbal_pb2'
  # @@protoc_insertion_point(class_scope:gimbal.GimbalCommand)
  })
_sym_db.RegisterMessage(GimbalCommand)

GimbalAxisControl = _reflection.GeneratedProtocolMessageType('GimbalAxisControl', (_message.Message,), {
  'DESCRIPTOR' : _GIMBALAXISCONTROL,
  '__module__' : 'gimbal_pb2'
  # @@protoc_insertion_point(class_scope:gimbal.GimbalAxisControl)
  })
_sym_db.RegisterMessage(GimbalAxisControl)

GimbalSyncTime = _reflection.GeneratedProtocolMessageType('GimbalSyncTime', (_message.Message,), {
  'DESCRIPTOR' : _GIMBALSYNCTIME,
  '__module__' : 'gimbal_pb2'
  # @@protoc_insertion_point(class_scope:gimbal.GimbalSyncTime)
  })
_sym_db.RegisterMessage(GimbalSyncTime)

GimbalSelfCheck = _reflection.GeneratedProtocolMessageType('GimbalSelfCheck', (_message.Message,), {
  'DESCRIPTOR' : _GIMBALSELFCHECK,
  '__module__' : 'gimbal_pb2'
  # @@protoc_insertion_point(class_scope:gimbal.GimbalSelfCheck)
  })
_sym_db.RegisterMessage(GimbalSelfCheck)

BinocularSelfCheck = _reflection.GeneratedProtocolMessageType('BinocularSelfCheck', (_message.Message,), {
  'DESCRIPTOR' : _BINOCULARSELFCHECK,
  '__module__' : 'gimbal_pb2'
  # @@protoc_insertion_point(class_scope:gimbal.BinocularSelfCheck)
  })
_sym_db.RegisterMessage(BinocularSelfCheck)

GimbalControl = _reflection.GeneratedProtocolMessageType('GimbalControl', (_message.Message,), {
  'DESCRIPTOR' : _GIMBALCONTROL,
  '__module__' : 'gimbal_pb2'
  # @@protoc_insertion_point(class_scope:gimbal.GimbalControl)
  })
_sym_db.RegisterMessage(GimbalControl)

BinocularControl = _reflection.GeneratedProtocolMessageType('BinocularControl', (_message.Message,), {
  'DESCRIPTOR' : _BINOCULARCONTROL,
  '__module__' : 'gimbal_pb2'
  # @@protoc_insertion_point(class_scope:gimbal.BinocularControl)
  })
_sym_db.RegisterMessage(BinocularControl)

GimbalStatus = _reflection.GeneratedProtocolMessageType('GimbalStatus', (_message.Message,), {
  'DESCRIPTOR' : _GIMBALSTATUS,
  '__module__' : 'gimbal_pb2'
  # @@protoc_insertion_point(class_scope:gimbal.GimbalStatus)
  })
_sym_db.RegisterMessage(GimbalStatus)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GIMBALCOMMAND._serialized_start=37
  _GIMBALCOMMAND._serialized_end=210
  _GIMBALAXISCONTROL._serialized_start=213
  _GIMBALAXISCONTROL._serialized_end=364
  _GIMBALSYNCTIME._serialized_start=366
  _GIMBALSYNCTIME._serialized_end=382
  _GIMBALSELFCHECK._serialized_start=384
  _GIMBALSELFCHECK._serialized_end=401
  _BINOCULARSELFCHECK._serialized_start=403
  _BINOCULARSELFCHECK._serialized_end=423
  _GIMBALCONTROL._serialized_start=426
  _GIMBALCONTROL._serialized_end=564
  _BINOCULARCONTROL._serialized_start=567
  _BINOCULARCONTROL._serialized_end=714
  _BINOCULARCONTROL_CONTROLTYPE._serialized_start=670
  _BINOCULARCONTROL_CONTROLTYPE._serialized_end=714
  _GIMBALSTATUS._serialized_start=717
  _GIMBALSTATUS._serialized_end=943
  _GIMBALSTATUS_GIMBALSTATE._serialized_start=862
  _GIMBALSTATUS_GIMBALSTATE._serialized_end=943
# @@protoc_insertion_point(module_scope)
