# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ota_update.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ota_update.proto\x12\x04h130\"\x83\x02\n\x10OtaUpdateRequest\x12\x33\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32#.h130.OtaUpdateRequest.ActionOption\x12/\n\x04type\x18\x02 \x01(\x0e\x32!.h130.OtaUpdateRequest.UpdateType\x12\x1b\n\x13update_package_path\x18\x03 \x01(\t\"5\n\x0c\x41\x63tionOption\x12\x12\n\x0eUPDATE_REQUEST\x10\x01\x12\x11\n\rREBOOT_SYSTEM\x10\x02\"5\n\nUpdateType\x12\x16\n\x12INCREMENTAL_UPDATE\x10\x01\x12\x0f\n\x0b\x46ULL_UPDATE\x10\x02\"\xa1\x01\n\x11OtaUpdateResponse\x12\x36\n\tota_error\x18\x01 \x01(\x0e\x32#.h130.OtaUpdateResponse.ErrorReason\x12\x12\n\nupdate_ack\x18\x02 \x01(\x08\"@\n\x0b\x45rrorReason\x12\x0f\n\x0bLOW_BATTERY\x10\x01\x12\x0f\n\x0bNO_CHARGING\x10\x02\x12\x0f\n\x0bOTHER_ERROR\x10\x03')



_OTAUPDATEREQUEST = DESCRIPTOR.message_types_by_name['OtaUpdateRequest']
_OTAUPDATERESPONSE = DESCRIPTOR.message_types_by_name['OtaUpdateResponse']
_OTAUPDATEREQUEST_ACTIONOPTION = _OTAUPDATEREQUEST.enum_types_by_name['ActionOption']
_OTAUPDATEREQUEST_UPDATETYPE = _OTAUPDATEREQUEST.enum_types_by_name['UpdateType']
_OTAUPDATERESPONSE_ERRORREASON = _OTAUPDATERESPONSE.enum_types_by_name['ErrorReason']
OtaUpdateRequest = _reflection.GeneratedProtocolMessageType('OtaUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _OTAUPDATEREQUEST,
  '__module__' : 'ota_update_pb2'
  # @@protoc_insertion_point(class_scope:h130.OtaUpdateRequest)
  })
_sym_db.RegisterMessage(OtaUpdateRequest)

OtaUpdateResponse = _reflection.GeneratedProtocolMessageType('OtaUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _OTAUPDATERESPONSE,
  '__module__' : 'ota_update_pb2'
  # @@protoc_insertion_point(class_scope:h130.OtaUpdateResponse)
  })
_sym_db.RegisterMessage(OtaUpdateResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OTAUPDATEREQUEST._serialized_start=27
  _OTAUPDATEREQUEST._serialized_end=286
  _OTAUPDATEREQUEST_ACTIONOPTION._serialized_start=178
  _OTAUPDATEREQUEST_ACTIONOPTION._serialized_end=231
  _OTAUPDATEREQUEST_UPDATETYPE._serialized_start=233
  _OTAUPDATEREQUEST_UPDATETYPE._serialized_end=286
  _OTAUPDATERESPONSE._serialized_start=289
  _OTAUPDATERESPONSE._serialized_end=450
  _OTAUPDATERESPONSE_ERRORREASON._serialized_start=386
  _OTAUPDATERESPONSE_ERRORREASON._serialized_end=450
# @@protoc_insertion_point(module_scope)
