# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rovio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brovio.proto\x12\trovioData\x1a\nbase.proto\"Z\n\x05Rovio\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x1d\n\x08position\x18\x02 \x01(\x0b\x32\x0b.base.Vec3f\x12\x1f\n\nquaternion\x18\x03 \x01(\x0b\x32\x0b.base.Vec4fb\x06proto3')



_ROVIO = DESCRIPTOR.message_types_by_name['Rovio']
Rovio = _reflection.GeneratedProtocolMessageType('Rovio', (_message.Message,), {
  'DESCRIPTOR' : _ROVIO,
  '__module__' : 'rovio_pb2'
  # @@protoc_insertion_point(class_scope:rovioData.Rovio)
  })
_sym_db.RegisterMessage(Rovio)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROVIO._serialized_start=38
  _ROVIO._serialized_end=128
# @@protoc_insertion_point(module_scope)
