# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_message_types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_types_pb2 as common__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17rpc_message_types.proto\x12\x04h130\x1a\x12\x63ommon_types.proto\")\n\x07\x42leName\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x10\n\x08usb_name\x18\x02 \x01(\t\"E\n\x13MediaCountsResponse\x12.\n\x0cmedia_counts\x18\x01 \x01(\x0b\x32\x18.h130.MediaCountsMessage\"N\n\x14\x43hargerStateResponse\x12\x1c\n\x14is_charger_connected\x18\x01 \x01(\x08\x12\x18\n\x10is_fully_charged\x18\x02 \x01(\x08\"c\n\x0f\x42oardIdResponse\x12\x10\n\x08\x62oard_id\x18\x01 \x02(\r\x12\x1e\n\x16hardware_major_version\x18\x02 \x02(\r\x12\x1e\n\x16hardware_minor_version\x18\x03 \x01(\r\"7\n\x12KeyExchangeMessage\x12\r\n\x05nonce\x18\x01 \x02(\x0c\x12\x12\n\npublic_key\x18\x02 \x02(\x0c\"M\n\x17PairingSignatureMessage\x12\x13\n\x0bsig_pairing\x18\x01 \x01(\x0c\x12\x1d\n\x15pairing_sc_cert_chain\x18\x02 \x03(\t\":\n\x17PeerVerificationMessage\x12\x0b\n\x03tag\x18\x01 \x02(\x0c\x12\x12\n\nciphertext\x18\x02 \x02(\x0c\"M\n\x0fRealTimeMessage\x12\x10\n\x08time_utc\x18\x01 \x02(\x04\x12\x11\n\ttime_zone\x18\x02 \x01(\x05\x12\x15\n\rtime_zone_str\x18\x03 \x01(\t\")\n\x16ValidatePairingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"?\n\x17ValidatePairingResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x14\n\x0cmedia_counts\x18\x02 \x01(\rB#\n\x16\x63n.zerozero.proto.h130P\x01\xa2\x02\x06H130PB')



_BLENAME = DESCRIPTOR.message_types_by_name['BleName']
_MEDIACOUNTSRESPONSE = DESCRIPTOR.message_types_by_name['MediaCountsResponse']
_CHARGERSTATERESPONSE = DESCRIPTOR.message_types_by_name['ChargerStateResponse']
_BOARDIDRESPONSE = DESCRIPTOR.message_types_by_name['BoardIdResponse']
_KEYEXCHANGEMESSAGE = DESCRIPTOR.message_types_by_name['KeyExchangeMessage']
_PAIRINGSIGNATUREMESSAGE = DESCRIPTOR.message_types_by_name['PairingSignatureMessage']
_PEERVERIFICATIONMESSAGE = DESCRIPTOR.message_types_by_name['PeerVerificationMessage']
_REALTIMEMESSAGE = DESCRIPTOR.message_types_by_name['RealTimeMessage']
_VALIDATEPAIRINGREQUEST = DESCRIPTOR.message_types_by_name['ValidatePairingRequest']
_VALIDATEPAIRINGRESPONSE = DESCRIPTOR.message_types_by_name['ValidatePairingResponse']
BleName = _reflection.GeneratedProtocolMessageType('BleName', (_message.Message,), {
  'DESCRIPTOR' : _BLENAME,
  '__module__' : 'rpc_message_types_pb2'
  # @@protoc_insertion_point(class_scope:h130.BleName)
  })
_sym_db.RegisterMessage(BleName)

MediaCountsResponse = _reflection.GeneratedProtocolMessageType('MediaCountsResponse', (_message.Message,), {
  'DESCRIPTOR' : _MEDIACOUNTSRESPONSE,
  '__module__' : 'rpc_message_types_pb2'
  # @@protoc_insertion_point(class_scope:h130.MediaCountsResponse)
  })
_sym_db.RegisterMessage(MediaCountsResponse)

ChargerStateResponse = _reflection.GeneratedProtocolMessageType('ChargerStateResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHARGERSTATERESPONSE,
  '__module__' : 'rpc_message_types_pb2'
  # @@protoc_insertion_point(class_scope:h130.ChargerStateResponse)
  })
_sym_db.RegisterMessage(ChargerStateResponse)

BoardIdResponse = _reflection.GeneratedProtocolMessageType('BoardIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOARDIDRESPONSE,
  '__module__' : 'rpc_message_types_pb2'
  # @@protoc_insertion_point(class_scope:h130.BoardIdResponse)
  })
_sym_db.RegisterMessage(BoardIdResponse)

KeyExchangeMessage = _reflection.GeneratedProtocolMessageType('KeyExchangeMessage', (_message.Message,), {
  'DESCRIPTOR' : _KEYEXCHANGEMESSAGE,
  '__module__' : 'rpc_message_types_pb2'
  # @@protoc_insertion_point(class_scope:h130.KeyExchangeMessage)
  })
_sym_db.RegisterMessage(KeyExchangeMessage)

PairingSignatureMessage = _reflection.GeneratedProtocolMessageType('PairingSignatureMessage', (_message.Message,), {
  'DESCRIPTOR' : _PAIRINGSIGNATUREMESSAGE,
  '__module__' : 'rpc_message_types_pb2'
  # @@protoc_insertion_point(class_scope:h130.PairingSignatureMessage)
  })
_sym_db.RegisterMessage(PairingSignatureMessage)

PeerVerificationMessage = _reflection.GeneratedProtocolMessageType('PeerVerificationMessage', (_message.Message,), {
  'DESCRIPTOR' : _PEERVERIFICATIONMESSAGE,
  '__module__' : 'rpc_message_types_pb2'
  # @@protoc_insertion_point(class_scope:h130.PeerVerificationMessage)
  })
_sym_db.RegisterMessage(PeerVerificationMessage)

RealTimeMessage = _reflection.GeneratedProtocolMessageType('RealTimeMessage', (_message.Message,), {
  'DESCRIPTOR' : _REALTIMEMESSAGE,
  '__module__' : 'rpc_message_types_pb2'
  # @@protoc_insertion_point(class_scope:h130.RealTimeMessage)
  })
_sym_db.RegisterMessage(RealTimeMessage)

ValidatePairingRequest = _reflection.GeneratedProtocolMessageType('ValidatePairingRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATEPAIRINGREQUEST,
  '__module__' : 'rpc_message_types_pb2'
  # @@protoc_insertion_point(class_scope:h130.ValidatePairingRequest)
  })
_sym_db.RegisterMessage(ValidatePairingRequest)

ValidatePairingResponse = _reflection.GeneratedProtocolMessageType('ValidatePairingResponse', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATEPAIRINGRESPONSE,
  '__module__' : 'rpc_message_types_pb2'
  # @@protoc_insertion_point(class_scope:h130.ValidatePairingResponse)
  })
_sym_db.RegisterMessage(ValidatePairingResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026cn.zerozero.proto.h130P\001\242\002\006H130PB'
  _BLENAME._serialized_start=53
  _BLENAME._serialized_end=94
  _MEDIACOUNTSRESPONSE._serialized_start=96
  _MEDIACOUNTSRESPONSE._serialized_end=165
  _CHARGERSTATERESPONSE._serialized_start=167
  _CHARGERSTATERESPONSE._serialized_end=245
  _BOARDIDRESPONSE._serialized_start=247
  _BOARDIDRESPONSE._serialized_end=346
  _KEYEXCHANGEMESSAGE._serialized_start=348
  _KEYEXCHANGEMESSAGE._serialized_end=403
  _PAIRINGSIGNATUREMESSAGE._serialized_start=405
  _PAIRINGSIGNATUREMESSAGE._serialized_end=482
  _PEERVERIFICATIONMESSAGE._serialized_start=484
  _PEERVERIFICATIONMESSAGE._serialized_end=542
  _REALTIMEMESSAGE._serialized_start=544
  _REALTIMEMESSAGE._serialized_end=621
  _VALIDATEPAIRINGREQUEST._serialized_start=623
  _VALIDATEPAIRINGREQUEST._serialized_end=664
  _VALIDATEPAIRINGRESPONSE._serialized_start=666
  _VALIDATEPAIRINGRESPONSE._serialized_end=729
# @@protoc_insertion_point(module_scope)
