# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import camera_pb2 as camera__pb2
import common_types_pb2 as common__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\x02pb\x1a\x0c\x63\x61mera.proto\x1a\x12\x63ommon_types.proto\"\x0b\n\tParamNone\"\x18\n\nCommandAck\x12\n\n\x02rc\x18\x01 \x01(\x05\x32\x8d\x05\n\x05Hover\x12\x34\n\x0cStartSession\x12\x11.camera.SessionId\x1a\x11.camera.SessionId\x12,\n\x0bStopSession\x12\r.pb.ParamNone\x1a\x0e.pb.CommandAck\x12\x35\n\x0eSetCameraParam\x12\x13.camera.SetMetadata\x1a\x0e.pb.CommandAck\x12\x31\n\x0eGetCameraParam\x12\r.pb.ParamNone\x1a\x10.camera.Metadata\x12\x35\n\x13RegisterCameraEvent\x12\r.pb.ParamNone\x1a\r.camera.Event0\x01\x12/\n\x0fReadCameraEvent\x12\r.pb.ParamNone\x1a\r.camera.Event\x12-\n\x0cStartPreview\x12\r.pb.ParamNone\x1a\x0e.pb.CommandAck\x12,\n\x0bStopPreview\x12\r.pb.ParamNone\x1a\x0e.pb.CommandAck\x12+\n\nStartVideo\x12\r.pb.ParamNone\x1a\x0e.pb.CommandAck\x12*\n\tStopVideo\x12\r.pb.ParamNone\x1a\x0e.pb.CommandAck\x12-\n\x0cTakeSnapshot\x12\r.pb.ParamNone\x1a\x0e.pb.CommandAck\x12-\n\x0cStopSnapshot\x12\r.pb.ParamNone\x1a\x0e.pb.CommandAck\x12:\n\rRockerControl\x12\x1a.h130.RockerControlCommand\x1a\r.pb.ParamNoneB/Z-drone_platform/interface_definition/proto/rpcb\x06proto3')



_PARAMNONE = DESCRIPTOR.message_types_by_name['ParamNone']
_COMMANDACK = DESCRIPTOR.message_types_by_name['CommandAck']
ParamNone = _reflection.GeneratedProtocolMessageType('ParamNone', (_message.Message,), {
  'DESCRIPTOR' : _PARAMNONE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:pb.ParamNone)
  })
_sym_db.RegisterMessage(ParamNone)

CommandAck = _reflection.GeneratedProtocolMessageType('CommandAck', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDACK,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:pb.CommandAck)
  })
_sym_db.RegisterMessage(CommandAck)

_HOVER = DESCRIPTOR.services_by_name['Hover']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-drone_platform/interface_definition/proto/rpc'
  _PARAMNONE._serialized_start=51
  _PARAMNONE._serialized_end=62
  _COMMANDACK._serialized_start=64
  _COMMANDACK._serialized_end=88
  _HOVER._serialized_start=91
  _HOVER._serialized_end=744
# @@protoc_insertion_point(module_scope)
