# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_calibrate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16sensor_calibrate.proto\x12\x10sensor_calibrate\"I\n\x0e\x43\x61librateStart\x12\x37\n\tdirection\x18\x01 \x01(\x0e\x32$.sensor_calibrate.CalibrateDirection\"\x0f\n\rCalibrateStop\"\xaf\x01\n\x16SensorCalibrateCommand\x12&\n\x02id\x18\x01 \x01(\x0e\x32\x1a.sensor_calibrate.SensorID\x12\x31\n\x05start\x18\x02 \x01(\x0b\x32 .sensor_calibrate.CalibrateStartH\x00\x12/\n\x04stop\x18\x03 \x01(\x0b\x32\x1f.sensor_calibrate.CalibrateStopH\x00\x42\t\n\x07\x63ommand\"\\\n\x0f\x43\x61librateResult\x12\x37\n\tdirection\x18\x01 \x01(\x0e\x32$.sensor_calibrate.CalibrateDirection\x12\x10\n\x08\x66inished\x18\x02 \x01(\x08\"\xbf\x01\n\rCalibrateInfo\x12\x32\n\x07results\x18\x01 \x03(\x0b\x32!.sensor_calibrate.CalibrateResult\x12\x37\n\tdirection\x18\x02 \x01(\x0e\x32$.sensor_calibrate.CalibrateDirection\x12/\n\x05state\x18\x03 \x01(\x0e\x32 .sensor_calibrate.CalibrateState\x12\x10\n\x08progress\x18\x04 \x01(\x02*O\n\x08SensorID\x12\x17\n\x13SENSOR_ID_IMU_6AXIS\x10\x00\x12\x17\n\x13SENSOR_ID_IMU_9AXIS\x10\x01\x12\x11\n\rSENSOR_ID_MAG\x10\x02*q\n\x12\x43\x61librateDirection\x12\x08\n\x04X_UP\x10\x00\x12\n\n\x06X_DOWN\x10\x01\x12\x08\n\x04Y_UP\x10\x02\x12\n\n\x06Y_DOWN\x10\x03\x12\x08\n\x04Z_UP\x10\x04\x12\n\n\x06Z_DOWN\x10\x05\x12\x0b\n\x07HORIZON\x10\x06\x12\x0c\n\x08VERTICAL\x10\x07*\x98\x02\n\x0e\x43\x61librateState\x12\x0b\n\x07\x43\x41LI_OK\x10\x00\x12\'\n\x1aMAG_CALI_AT_WRONG_ATTITUDE\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12(\n\x1bMAG_CALI_COLLECT_DATA_ERROR\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12)\n\x1cMAG_CALI_IN_ENV_INTERFERENCE\x10\xfd\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12(\n\x1bMAG_CALI_PLANE_WINGS_CLOSED\x10\xfc\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12,\n\x1fMAG_CALI_PARAMS_RESULT_ABNORMAL\x10\xfb\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12#\n\x16MAG_CALI_RECV_STOP_CMD\x10\xfa\xff\xff\xff\xff\xff\xff\xff\xff\x01\x42\x15P\x01\xa2\x02\x10SENSOR_CALIBRATEb\x06proto3')

_SENSORID = DESCRIPTOR.enum_types_by_name['SensorID']
SensorID = enum_type_wrapper.EnumTypeWrapper(_SENSORID)
_CALIBRATEDIRECTION = DESCRIPTOR.enum_types_by_name['CalibrateDirection']
CalibrateDirection = enum_type_wrapper.EnumTypeWrapper(_CALIBRATEDIRECTION)
_CALIBRATESTATE = DESCRIPTOR.enum_types_by_name['CalibrateState']
CalibrateState = enum_type_wrapper.EnumTypeWrapper(_CALIBRATESTATE)
SENSOR_ID_IMU_6AXIS = 0
SENSOR_ID_IMU_9AXIS = 1
SENSOR_ID_MAG = 2
X_UP = 0
X_DOWN = 1
Y_UP = 2
Y_DOWN = 3
Z_UP = 4
Z_DOWN = 5
HORIZON = 6
VERTICAL = 7
CALI_OK = 0
MAG_CALI_AT_WRONG_ATTITUDE = -1
MAG_CALI_COLLECT_DATA_ERROR = -2
MAG_CALI_IN_ENV_INTERFERENCE = -3
MAG_CALI_PLANE_WINGS_CLOSED = -4
MAG_CALI_PARAMS_RESULT_ABNORMAL = -5
MAG_CALI_RECV_STOP_CMD = -6


_CALIBRATESTART = DESCRIPTOR.message_types_by_name['CalibrateStart']
_CALIBRATESTOP = DESCRIPTOR.message_types_by_name['CalibrateStop']
_SENSORCALIBRATECOMMAND = DESCRIPTOR.message_types_by_name['SensorCalibrateCommand']
_CALIBRATERESULT = DESCRIPTOR.message_types_by_name['CalibrateResult']
_CALIBRATEINFO = DESCRIPTOR.message_types_by_name['CalibrateInfo']
CalibrateStart = _reflection.GeneratedProtocolMessageType('CalibrateStart', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATESTART,
  '__module__' : 'sensor_calibrate_pb2'
  # @@protoc_insertion_point(class_scope:sensor_calibrate.CalibrateStart)
  })
_sym_db.RegisterMessage(CalibrateStart)

CalibrateStop = _reflection.GeneratedProtocolMessageType('CalibrateStop', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATESTOP,
  '__module__' : 'sensor_calibrate_pb2'
  # @@protoc_insertion_point(class_scope:sensor_calibrate.CalibrateStop)
  })
_sym_db.RegisterMessage(CalibrateStop)

SensorCalibrateCommand = _reflection.GeneratedProtocolMessageType('SensorCalibrateCommand', (_message.Message,), {
  'DESCRIPTOR' : _SENSORCALIBRATECOMMAND,
  '__module__' : 'sensor_calibrate_pb2'
  # @@protoc_insertion_point(class_scope:sensor_calibrate.SensorCalibrateCommand)
  })
_sym_db.RegisterMessage(SensorCalibrateCommand)

CalibrateResult = _reflection.GeneratedProtocolMessageType('CalibrateResult', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATERESULT,
  '__module__' : 'sensor_calibrate_pb2'
  # @@protoc_insertion_point(class_scope:sensor_calibrate.CalibrateResult)
  })
_sym_db.RegisterMessage(CalibrateResult)

CalibrateInfo = _reflection.GeneratedProtocolMessageType('CalibrateInfo', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATEINFO,
  '__module__' : 'sensor_calibrate_pb2'
  # @@protoc_insertion_point(class_scope:sensor_calibrate.CalibrateInfo)
  })
_sym_db.RegisterMessage(CalibrateInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001\242\002\020SENSOR_CALIBRATE'
  _SENSORID._serialized_start=602
  _SENSORID._serialized_end=681
  _CALIBRATEDIRECTION._serialized_start=683
  _CALIBRATEDIRECTION._serialized_end=796
  _CALIBRATESTATE._serialized_start=799
  _CALIBRATESTATE._serialized_end=1079
  _CALIBRATESTART._serialized_start=44
  _CALIBRATESTART._serialized_end=117
  _CALIBRATESTOP._serialized_start=119
  _CALIBRATESTOP._serialized_end=134
  _SENSORCALIBRATECOMMAND._serialized_start=137
  _SENSORCALIBRATECOMMAND._serialized_end=312
  _CALIBRATERESULT._serialized_start=314
  _CALIBRATERESULT._serialized_end=406
  _CALIBRATEINFO._serialized_start=409
  _CALIBRATEINFO._serialized_end=600
# @@protoc_insertion_point(module_scope)
