# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webp_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ewebp_rpc.proto\x12\x04h130\"\x1c\n\x0eWebpCommandAck\x12\n\n\x02rc\x18\x01 \x01(\x05\"\x84\x01\n\x11WebpNameToProcess\x12\x11\n\twebp_path\x18\x01 \x01(\t\x12\x12\n\nvideo_name\x18\x02 \x01(\t\x12\x12\n\nwebp_count\x18\x03 \x01(\x05\x12\x11\n\tjpeg_name\x18\x04 \x01(\t\x12\r\n\x05\x61ngle\x18\x05 \x01(\x02\x12\x12\n\njpeg_count\x18\x06 \x01(\x02\x32\x83\x02\n\x07WebpRpc\x12?\n\x0eNotifyJpegName\x12\x17.h130.WebpNameToProcess\x1a\x14.h130.WebpCommandAck\x12>\n\rNotifyYuvName\x12\x17.h130.WebpNameToProcess\x1a\x14.h130.WebpCommandAck\x12;\n\nStartVideo\x12\x17.h130.WebpNameToProcess\x1a\x14.h130.WebpCommandAck\x12:\n\tStopVideo\x12\x17.h130.WebpNameToProcess\x1a\x14.h130.WebpCommandAck')



_WEBPCOMMANDACK = DESCRIPTOR.message_types_by_name['WebpCommandAck']
_WEBPNAMETOPROCESS = DESCRIPTOR.message_types_by_name['WebpNameToProcess']
WebpCommandAck = _reflection.GeneratedProtocolMessageType('WebpCommandAck', (_message.Message,), {
  'DESCRIPTOR' : _WEBPCOMMANDACK,
  '__module__' : 'webp_rpc_pb2'
  # @@protoc_insertion_point(class_scope:h130.WebpCommandAck)
  })
_sym_db.RegisterMessage(WebpCommandAck)

WebpNameToProcess = _reflection.GeneratedProtocolMessageType('WebpNameToProcess', (_message.Message,), {
  'DESCRIPTOR' : _WEBPNAMETOPROCESS,
  '__module__' : 'webp_rpc_pb2'
  # @@protoc_insertion_point(class_scope:h130.WebpNameToProcess)
  })
_sym_db.RegisterMessage(WebpNameToProcess)

_WEBPRPC = DESCRIPTOR.services_by_name['WebpRpc']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WEBPCOMMANDACK._serialized_start=24
  _WEBPCOMMANDACK._serialized_end=52
  _WEBPNAMETOPROCESS._serialized_start=55
  _WEBPNAMETOPROCESS._serialized_end=187
  _WEBPRPC._serialized_start=190
  _WEBPRPC._serialized_end=449
# @@protoc_insertion_point(module_scope)
